# sync-models.ps1 - reconcile Ollama with models.json (the single source of truth).
# Replaces six near-identical hand-written .Modelfile files and six copy-pasted install blocks: the
# -cc variants (base model + a raised num_ctx, which the agent loop requires) are GENERATED from the
# manifest. Adding a model is now a single JSON entry.
#
#   sync-models.ps1                 pull autoPull bases, build every -cc variant whose base is present
#   sync-models.ps1 -All            also pull bases that are not marked autoPull (large downloads!)
#   sync-models.ps1 -Only coder     just one alias (or its -cc name)
#   sync-models.ps1 -Report         report only - change nothing
#
# Safe to re-run: 'ollama create' is idempotent.

# CmdletBinding so a MISTYPED parameter is an ERROR. A script with a plain param() block is not an
# ADVANCED function, so PowerShell silently drops unmatched arguments into $args instead of failing:
# `-Path C:\x` on a script whose parameter is -ProjectDir ran against the DEFAULT (the current
# directory). That is how a stray scaffold - CLAUDE.md, .mcp.json, docs\, git init - landed in the
# wrong folder. These scripts are invoked by MODELS, which typo parameter names.
[CmdletBinding()]
param(
  [switch]$All,
  [string]$Only = "",
  [switch]$Report
)
$ErrorActionPreference = "Stop"
$kit = $PSScriptRoot
$manifestPath = Join-Path $kit "models.json"
if (-not (Test-Path $manifestPath)) { throw "models.json not found next to sync-models.ps1" }
$mf = Get-Content $manifestPath -Raw | ConvertFrom-Json

if (-not (Get-Command ollama -ErrorAction SilentlyContinue)) {
  Write-Host "ollama not found on PATH - install it, then re-run (winget install Ollama.Ollama)" -ForegroundColor Yellow
  exit 1
}

# 'ollama list' is the ground truth for what exists locally.
$prevEap = $ErrorActionPreference; $ErrorActionPreference = "Continue"
$installed = (ollama list | Out-String)
$ErrorActionPreference = $prevEap
function Test-Model([string]$n) { return $installed -match [regex]::Escape($n) }

$targets = $mf.models
if ($Only) { $targets = $mf.models | Where-Object { $_.alias -eq $Only -or $_.name -eq $Only }
             if (-not $targets) { throw "no model in models.json matches '$Only'" } }

# The VRAM budget does not vary per model - resolve it ONCE, here, so the report below can print it
# without an inline if. `$((if(...){...}else{...}))` looks harmless but the inner parens make it an
# EXPRESSION context, where `if` is read as a command name: "The term 'if' is not recognized".
$vramBudget = 16
if ($mf.assumeVramGb) { $vramBudget = $mf.assumeVramGb }

$rows = New-Object System.Collections.Generic.List[object]
foreach ($m in $targets) {
  $numCtx = if ($m.PSObject.Properties.Name -contains 'numCtx' -and $m.numCtx) { $m.numCtx } else { $mf.numCtx }
  $baseHere = Test-Model $m.from
  $action = ""

  if (-not $Report) {
    if (-not $baseHere -and ($m.autoPull -or $All)) {
      Write-Host "  pulling $($m.from) ..." -ForegroundColor Cyan
      try { ollama pull $m.from | Out-Null; $baseHere = $true; $action = "pulled base" }
      catch { $action = "pull FAILED" }
    }
    if ($baseHere) {
      # Generate the Modelfile on the fly - nothing to keep in sync by hand.
      $tmp = Join-Path ([System.IO.Path]::GetTempPath()) ("adkit-$($m.name).Modelfile")
      $body = "# generated by sync-models.ps1 from models.json - do not hand-edit`r`n" +
              "FROM $($m.from)`r`nPARAMETER num_ctx $numCtx`r`n"
      [System.IO.File]::WriteAllText($tmp, $body, (New-Object System.Text.UTF8Encoding($false)))
      try {
        ollama create $m.name -f $tmp | Out-Null
        $action = if ($action) { "$action + built" } else { "built" }
      } catch { $action = "create FAILED: $($_.Exception.Message)" }
      finally { Remove-Item $tmp -ErrorAction SilentlyContinue }
    } elseif (-not $baseHere) {
      $action = "skipped (base not pulled)"
    }
    $installed = (ollama list | Out-String)   # refresh so the report reflects what we just did
  }

  # Fit = WEIGHTS + KV CACHE vs the VRAM budget. Weights alone is misleading: at 64K the cache adds
  # a few GB, which is what pushes several "14 GB" models over a 16 GB card.
  # Plain statements, NOT a multi-line `$x = if ... <newline> elseif ...`: PowerShell ends the
  # assignment at the closing brace, so the elseif on the next line is parsed as a COMMAND and blows up
  # at runtime with "the term 'elseif' is not recognized". It parses clean, which is why it shipped.
  $kvGb = 0
  if ($mf.kvCacheGbAt64k) { $kvGb = $mf.kvCacheGbAt64k }
  if (($m.PSObject.Properties.Name -contains 'kvGb') -and $m.kvGb) { $kvGb = $m.kvGb }   # per-model wins
  $effGb = $m.approxVramGb + $kvGb
  $fit = "offloads"                                                   # widest case first,
  if ($effGb -le ($vramBudget + 1)) { $fit = "BORDERLINE" }           # then narrower,
  if (($effGb + 1.5) -le $vramBudget) { $fit = "fits GPU" }           # narrowest wins

  $rows.Add([pscustomobject]@{
    Alias   = $m.alias
    Variant = $m.name
    Base    = $m.from
    Weights = "$($m.approxVramGb) GB"
    PlusKV  = "$effGb GB"
    Fit     = $fit
    Present = if (Test-Model $m.name) { "yes" } else { "NO" }
    Action  = if ($Report) { "-" } else { $action }
  })
}

Write-Host ""
$rows | Format-Table -AutoSize
if ($rows | Where-Object { $_.Fit -eq "BORDERLINE" }) {
  Write-Host "BORDERLINE = weights + KV cache land within ~1 GB of your $vramBudget GB card." -ForegroundColor Yellow
  Write-Host "             It usually runs, but expect partial offload - your results may vary. Lower numCtx in" -ForegroundColor Yellow
  Write-Host "             models.json (32768) to pull it back onto the GPU." -ForegroundColor Yellow
}
Write-Host "Switch with: use-model.cmd <alias>   (then start a NEW Claude Code session)" -ForegroundColor Green
$missing = $rows | Where-Object { $_.Present -eq "NO" }
if ($missing) {
  Write-Host ""
  Write-Host "Not built yet: $(($missing.Alias) -join ', ')" -ForegroundColor Yellow
  Write-Host "  pull the base first, e.g.  ollama pull $(($mf.models | Where-Object { $_.alias -eq $missing[0].Alias }).from)" -ForegroundColor Yellow
  Write-Host "  then re-run sync-models.cmd   (or 'sync-models.cmd -All' to pull everything - large!)" -ForegroundColor Yellow
}

# Supporting models (not chat models - used by the RAG/vision tools).
if (-not $Report) {
  foreach ($s in @($mf.embedModel, $mf.visionModel, $mf.smallFastModel) | Select-Object -Unique) {
    if ($s -and -not (Test-Model $s)) {
      Write-Host "  pulling support model $s ..." -ForegroundColor Cyan
      try { ollama pull $s | Out-Null } catch { Write-Host "  ($s pull failed - skipped)" -ForegroundColor Yellow }
    }
  }
}
exit 0
